# StockBot Advisor Configuration
# Complete configuration with 33 stocks across 4 sectors + benchmarks

app:
  name: "StockBot Advisor"
  version: "1.0.0"
  description: "AI-Powered Investment Advisory System"
  author: "Anthony Winata Salim"
  
# Stock Universe - 33 stocks + 4 ETFs
stocks:
  technology:
    - symbol: "AAPL"
      name: "Apple Inc."
      sector: "Technology"
    - symbol: "MSFT"
      name: "Microsoft Corporation"
      sector: "Technology"
    - symbol: "GOOGL"
      name: "Alphabet Inc."
      sector: "Technology"
    - symbol: "NVDA"
      name: "NVIDIA Corporation"
      sector: "Technology"
    - symbol: "META"
      name: "Meta Platforms Inc."
      sector: "Technology"
    - symbol: "PLTR"
      name: "Palantir Technologies"
      sector: "Technology"
  
  financial:
    # Original 5 stocks
    - symbol: "JPM"
      name: "JPMorgan Chase & Co."
      sector: "Banking"
    - symbol: "BAC"
      name: "Bank of America"
      sector: "Banking"
    - symbol: "GS"
      name: "Goldman Sachs"
      sector: "Banking"
    - symbol: "MS"
      name: "Morgan Stanley"
      sector: "Banking"
    - symbol: "V"
      name: "Visa Inc."
      sector: "Financial Services"
    # Additional 5 financial stocks
    - symbol: "MA"
      name: "Mastercard Inc."
      sector: "Financial Services"
    - symbol: "WFC"
      name: "Wells Fargo & Company"
      sector: "Banking"
    - symbol: "AXP"
      name: "American Express"
      sector: "Financial Services"
    - symbol: "BLK"
      name: "BlackRock Inc."
      sector: "Financial Services"
    - symbol: "SPGI"
      name: "S&P Global Inc."
      sector: "Financial Services"
  
  real_estate:
    - symbol: "PLD"
      name: "Prologis Inc."
      sector: "Real Estate"
      subsector: "Industrial REITs"
    - symbol: "AMT"
      name: "American Tower Corp"
      sector: "Real Estate"
      subsector: "Infrastructure REITs"
    - symbol: "EQIX"
      name: "Equinix Inc."
      sector: "Real Estate"
      subsector: "Data Center REITs"
    - symbol: "SPG"
      name: "Simon Property Group"
      sector: "Real Estate"
      subsector: "Retail REITs"
    - symbol: "O"
      name: "Realty Income Corp"
      sector: "Real Estate"
      subsector: "Retail REITs"
  
  healthcare:
    - symbol: "JNJ"
      name: "Johnson & Johnson"
      sector: "Healthcare"
    - symbol: "PFE"
      name: "Pfizer Inc."
      sector: "Healthcare"
    - symbol: "MRNA"
      name: "Moderna Inc."
      sector: "Healthcare"
    - symbol: "UNH"
      name: "UnitedHealth Group"
      sector: "Healthcare"
  
  benchmarks:
    - symbol: "SPY"
      name: "SPDR S&P 500 ETF"
      type: "ETF"
    - symbol: "QQQ"
      name: "Invesco QQQ Trust"
      type: "ETF"
    - symbol: "DIA"
      name: "SPDR Dow Jones Industrial Average ETF"
      type: "ETF"
    - symbol: "VNQ"
      name: "Vanguard Real Estate ETF"
      type: "REIT ETF"

# Technical Indicators Configuration
technical_indicators:
  rsi:
    period: 14
    overbought: 70
    oversold: 30
  
  macd:
    fast_period: 12
    slow_period: 26
    signal_period: 9
  
  moving_averages:
    sma_short: 20
    sma_long: 50
    ema_short: 12
    ema_long: 26
  
  bollinger_bands:
    period: 20
    std_dev: 2
  
  stochastic:
    k_period: 14
    d_period: 3
    overbought: 80
    oversold: 20
  
  atr:
    period: 14

# Machine Learning Configuration
ml_config:
  model_type: "RandomForest"
  parameters:
    n_estimators: 300
    max_depth: 12
    min_samples_split: 10
    min_samples_leaf: 4
    max_features: "sqrt"
    random_state: 42
    
    # Gradient Boosting parameters
    gb_n_estimators: 200
    gb_max_depth: 8
    gb_learning_rate: 0.1
    gb_subsample: 0.8
    
    # XGBoost parameters (if available)
    xgb_n_estimators: 250
    xgb_max_depth: 6
    xgb_learning_rate: 0.1
    xgb_subsample: 0.8
  
  features:
    - "RSI"
    - "MACD"
    - "MACD_Signal"
    - "BB_Position"
    - "Stochastic_K"
    - "Volume_Ratio"
    - "ATR"
    - "SMA_20"
    - "SMA_50"
    - "EMA_12"
    - "EMA_26"
    - "Volume_MA"
    - "High_Low_Spread"
    - "Close_Open_Spread"
  
  training:
    test_size: 0.2
    lookback_period: 90
    prediction_horizon: 5
    confidence_threshold: 0.70
    cv_folds: 5
    handle_imbalance: true
    use_ensemble: true
    calibrate_probabilities: true
    feature_selection: true
    n_features: 50
    selection_method: "mutual_info"

# Signal Generation
signals:
  buy_threshold: 0.02
  sell_threshold: -0.02
  hold_range: [-0.02, 0.02]
  
  confidence_levels:
    high: 0.70
    medium: 0.60
    low: 0.45

# Risk Management
risk_management:
  max_position_size: 0.10
  stop_loss: 0.05
  take_profit: 0.15
  
  risk_levels:
    conservative:
      volatility_cap: 0.15
      max_drawdown: 0.10
      position_limit: 5
    
    moderate:
      volatility_cap: 0.25
      max_drawdown: 0.15
      position_limit: 8
    
    aggressive:
      volatility_cap: 0.35
      max_drawdown: 0.25
      position_limit: 12

# Data Configuration
data:
  default_period: "3y"
  update_frequency: 300
  cache_duration: 3600
  
  periods:
    - "1d"
    - "5d"
    - "1mo"
    - "3mo"
    - "6mo"
    - "1y"
    - "2y"
    - "3y"
    - "5y"
  
  intervals:
    - "1m"
    - "5m"
    - "15m"
    - "30m"
    - "1h"
    - "1d"
    - "1wk"
    - "1mo"

# User Interface Configuration
ui:
  theme: "minimal"
  color_scheme:
    primary: "#000000"
    secondary: "#6C757D"
    background: "#FFFFFF"
    surface: "#F8F9FA"
    border: "#E9ECEF"
    success: "#28A745"
    danger: "#DC3545"
    warning: "#FFC107"
    info: "#17A2B8"

# Backtesting Configuration
backtesting:
  strategies:
    - "MA Crossover"
    - "RSI Mean Reversion"
    - "MACD Momentum"
    - "Bollinger Bands"
    - "ML-Based (Enhanced)"
  
  commission: 0.001
  slippage: 0.0005
  initial_capital: 100000
  
  performance_metrics:
    - "total_return"
    - "sharpe_ratio"
    - "max_drawdown"
    - "win_rate"
    - "profit_factor"

# Dashboard Configuration
dashboard:
  default_view: "overview"
  refresh_interval: 60
  
  widgets:
    - "portfolio_summary"
    - "market_overview"
    - "top_movers"
    - "ai_signals"
    - "risk_metrics"
    - "news_feed"
  
  chart_settings:
    default_period: "1d"
    candlestick: true
    volume: true
    indicators: ["SMA_20", "SMA_50", "RSI"]

# Notification Settings
notifications:
  enable_email: false
  enable_push: false
  enable_in_app: true
  
  triggers:
    - "high_confidence_signal"
    - "stop_loss_hit"
    - "portfolio_rebalance"
    - "large_price_movement"

# Database Configuration
database:
  type: "sqlite"
  path: "data/stockbot.db"
  
  tables:
    - "portfolio"
    - "transactions"
    - "predictions"
    - "backtest_results"
    - "user_settings"

# API Configuration
api:
  yfinance:
    rate_limit: 2000
    timeout: 30
  
  sentiment:
    enabled: false
    provider: "newsapi"
    
# Logging Configuration
logging:
  level: "INFO"
  file: "logs/stockbot.log"
  max_size: "10MB"
  backup_count: 5

# Performance Optimization
optimization:
  cache_enabled: true
  parallel_processing: true
  batch_size: 100
  memory_limit: "2GB"